# Generated by Django 3.1.4 on 2020-12-17 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='accounts',
            field=models.ManyToManyField(to='accounts.Account'),
        ),
    ]
