# Generated by Django 3.1.4 on 2020-12-19 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_auto_20201219_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cuit',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
    ]
